BEGIN TRANSACTION;

UPDATE imitmadt_sql
SET item_desc_1 = item_desc_2,
    item_desc_2 = item_desc_1
WHERE item_desc_2 IS NOT NULL
  AND item_desc_2 <> 'NULL'
  AND LTRIM(RTRIM(item_desc_2)) <> ''
  AND (item_desc_1 LIKE '%[0-9] x %' 
       OR item_desc_1 LIKE '%[0-9]x%' 
       OR item_desc_1 LIKE '%[0-9] X %'
       OR item_desc_1 LIKE '%[0-9]X%')
  AND item_desc_1 NOT LIKE '%ACRY%'
  AND item_desc_1 NOT LIKE '%PVC%'
  AND item_desc_1 NOT LIKE '%HDPE%'
  AND item_desc_1 NOT LIKE '%LDPE%'
  AND item_desc_1 NOT LIKE '%UHMW%'
  AND item_desc_1 NOT LIKE '%NYLON%'
  AND item_desc_1 NOT LIKE '%POLY%'
  AND item_desc_1 NOT LIKE '%ABS%'
  AND item_desc_1 NOT LIKE '%NAT%'
  AND item_desc_1 NOT LIKE '%BLACK%'
  AND item_desc_1 NOT LIKE '%BLK%'
  AND item_desc_1 NOT LIKE '%WHITE%'
  AND item_desc_1 NOT LIKE '%WH%'
  AND item_desc_1 NOT LIKE '%CLEAR%'
  AND item_desc_1 NOT LIKE '%CL.%'
  AND item_desc_1 NOT LIKE '%GRAY%'
  AND item_desc_1 NOT LIKE '%GREY%'
  AND item_desc_1 NOT LIKE '%GREEN%'
  AND item_desc_1 NOT LIKE '%BLUE%'
  AND item_desc_1 NOT LIKE '%RED%'
  AND item_desc_1 NOT LIKE '%BRONZE%'
  AND item_desc_1 NOT LIKE '%BRZ%'
  AND item_desc_1 NOT LIKE '%AMBER%'
  AND item_desc_1 NOT LIKE '%PURPLE%'
  AND item_desc_1 NOT LIKE '%YELLOW%'
  AND item_desc_1 NOT LIKE '%ROSE%'
  AND item_desc_1 NOT LIKE '%TAN%'
  AND item_desc_1 NOT LIKE '%BEIGE%'
  AND item_desc_1 NOT LIKE '%BORATED%'
  AND item_desc_1 NOT LIKE '%PHENOLIC%'
  AND item_desc_1 NOT LIKE '%CANVAS%'
  AND item_desc_1 NOT LIKE '%KYDEX%'
  AND item_desc_1 NOT LIKE '%BOLTARON%'
  AND item_desc_1 NOT LIKE '%RULON%'
  AND item_desc_1 NOT LIKE '%ULTEM%'
  AND item_desc_1 NOT LIKE '%LEXAN%'
  AND item_desc_1 NOT LIKE '%LUCITE%'
  AND item_desc_1 NOT LIKE '%PETG%'
  AND item_desc_1 NOT LIKE '%VIVAK%'
  AND item_desc_1 NOT LIKE '%DELRIN%'
  AND item_desc_1 NOT LIKE '%ACETAL%'
  AND item_desc_1 NOT LIKE '%ARDEL%'
  AND item_desc_1 NOT LIKE '%COROPLAST%'
  AND item_desc_1 NOT LIKE '%STARBOARD%'
  AND item_desc_1 NOT LIKE '%SEABOARD%'
  AND item_desc_1 NOT LIKE '%KOMATEX%'
  AND item_desc_1 NOT LIKE '%CELTEC%'
  AND item_desc_1 NOT LIKE '%FOAM%'
  AND item_desc_1 NOT LIKE '%PLAQUE%'
  AND item_desc_1 NOT LIKE '%TUBE%'
  AND item_desc_1 NOT LIKE '%SHEET%'
  AND item_desc_1 NOT LIKE '%MIRROR%'
  AND item_desc_1 NOT LIKE '%P-95%'
  AND item_desc_1 NOT LIKE '%P95%'
  AND item_desc_1 NOT LIKE '%MARGACIPTA%'
  AND item_desc_1 NOT LIKE '%FILLED%'
  AND item_desc_1 NOT LIKE '%PE %'
  AND item_desc_1 NOT LIKE '%PP %'
  AND item_desc_1 NOT LIKE '%PC %';
